-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-24 06:48:44 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE country (
    countryname VARCHAR2(35 CHAR) NOT NULL
);

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( countryname );

CREATE TABLE olympiad (
    year NUMBER(4) NOT NULL
);

ALTER TABLE olympiad ADD CONSTRAINT olympiad_pk PRIMARY KEY ( year );

CREATE TABLE participant (
    participant_id       NUMBER(6) NOT NULL,
    firstname            VARCHAR2(255 CHAR),
    lastname             VARCHAR2(255 CHAR),
    countryname          VARCHAR2(35 CHAR) NOT NULL
);

ALTER TABLE participant ADD CONSTRAINT participant_pk PRIMARY KEY ( participant_id );

CREATE TABLE participation (
    participant_id  NUMBER(6) NOT NULL,
    year               NUMBER(4) NOT NULL
);

ALTER TABLE participation ADD CONSTRAINT participation_pk PRIMARY KEY ( participant_id, year );

CREATE TABLE problem (
    problem_id     NUMBER(4) NOT NULL,
    year  NUMBER(4) NOT NULL
);

ALTER TABLE problem ADD CONSTRAINT problem_pk PRIMARY KEY ( problem_id );

CREATE TABLE solution (
    solution        VARCHAR2(35) NOT NULL,
    participant_id  NUMBER(6) NOT NULL,
    problem_id      NUMBER(4) NOT NULL,
    mark            INT NOT NULL
);

ALTER TABLE participant
    ADD CONSTRAINT participant_country_fk FOREIGN KEY ( countryname )
        REFERENCES country ( countryname );

ALTER TABLE problem
    ADD CONSTRAINT problem_olympiad_fk FOREIGN KEY ( year )
        REFERENCES olympiad ( year );

ALTER TABLE participation
    ADD CONSTRAINT participation_olympiad_fk FOREIGN KEY ( year )
        REFERENCES olympiad ( year );

ALTER TABLE participation
    ADD CONSTRAINT participation_participant_fk FOREIGN KEY ( participant_id )
        REFERENCES participant ( participant_id );

ALTER TABLE solution
    ADD CONSTRAINT solution_participant_fk FOREIGN KEY ( participant_id )
        REFERENCES participant ( participant_id );

ALTER TABLE solution
    ADD CONSTRAINT solution_problem_fk FOREIGN KEY ( problem_id )
        REFERENCES problem ( problem_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
